# Generated by Django 5.1.2 on 2024-10-30 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dateEdit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
