# Generated by Django 5.1.1 on 2024-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(choices=[('Accounting', 'Accounting'), ('Checker', 'Checker'), ('Driver', 'Driver'), ('Guard', 'Guard'), ('Sales Agent', 'Sales Agent'), ('Secretary', 'Secretary'), ('Warehouse Helper', 'Warehouse Helper')], max_length=50)),
                ('dateStart', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
