# Generated by Django 5.1.3 on 2024-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
