# Generated by Django 5.1.3 on 2024-11-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_status_purchaseitem_delivered_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('cargo_name', models.CharField(max_length=100)),
                ('cargo_number', models.CharField(max_length=50)),
                ('shipment_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('term', models.CharField(choices=[('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='30 Days', max_length=10)),
                ('checked_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='purchases.purchase')),
            ],
        ),
    ]
