# Generated by Django 5.1.3 on 2024-11-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn'),
        ),
    ]
