# Generated by Django 5.1.3 on 2024-11-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Damaged', 'Damaged')], default='Available', max_length=50)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialized_items', to='inventory.inventory')),
            ],
        ),
    ]
