# Generated by Django 5.1.1 on 2024-11-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_status'),
        ('inventory', '0002_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer'),
        ),
    ]
