# Generated by Django 5.1.1 on 2024-11-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='customer',
            new_name='customer_hardware',
        ),
    ]
