# Generated by Django 5.1.1 on 2024-11-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_customer_inventory_customer_hardware'),
        ('products', '0005_product_purchase_price'),
        ('purchases', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='purchases.purchase'),
        ),
    ]
