# Generated by Django 5.1.2 on 2024-10-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_hardware', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('dateStart', models.DateField(verbose_name='Date Started')),
                ('startBy', models.CharField(choices=[('Office', 'Office'), ('Agent', 'Agent')], max_length=10)),
            ],
        ),
    ]
