# Generated by Django 5.1.2 on 2024-11-01 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dateEdit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
