# Generated by Django 5.1.1 on 2024-11-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_saleitem_delete_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
    ]
