# Generated by Django 5.1.1 on 2024-11-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_customer_address_remove_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_hardware',
            new_name='customer',
        ),
    ]
