# Generated by Django 5.1.1 on 2024-11-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_status'),
        ('sales', '0009_rename_customer_hardware_customer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='customers.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
