# Generated by Django 5.1.1 on 2024-11-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sales_customer_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='payment_status',
            new_name='payment_stat',
        ),
    ]
