# Generated by Django 5.1.1 on 2024-11-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_status'),
        ('sales', '0011_rename_payment_status_sales_payment_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_code',
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer'),
        ),
    ]
