# Generated by Django 5.1.3 on 2024-11-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=100),
        ),
    ]
