# Generated by Django 5.1.3 on 2024-11-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
