# Generated by Django 5.1.3 on 2024-11-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
    ]
