# Generated by Django 5.1.3 on 2024-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
    ]
