# Generated by Django 5.1.1 on 2024-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
